baseURL = "https://vonv.tk/"
title = "Vassago's Blog"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2015-{year} Ars Von Geotia. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true # If you use only one language comment this option
disableLanguages = ["fr", "zh-tw"] # For disable one or more language

# Pagination
paginate = 7
# paginatePath = "page"

# Disqus
disqusShortname = "disqus_LCyGJbOccq"

# Google analytics
googleAnalytics = "UA-151521286-1"

enableRobotsTXT = true

enableEmoji = true

hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
