email = "ars.von.roseregen@gmail.com"
# facebook = "yourfacebookusername"
github = "vonsago"
# gitlab = "yourgitlabusername"
linkedin = "yourlinkedinusername"
stackoverflow = "7369431"
twitter = "V_assago"
reddit = "yourredditusername"
telegram = "yourtelegramusername"
dockerhub = "yourdockerhubusername"
bitbucket = "yourbitbucketworkspaceid"
kaggle = "yourkaggleusername"
medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
lastfm = "yourlastfmusername"
bilibili = "38811864"
youtube = "youryoutubechannelid"
discord = "yourdiscordinvitecode"
discourse = "https://yourforum.tld"
pinterest = "yourpinterestusername"
